tap "github/bootstrap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "neovim/neovim"
cask "java"
brew "autoconf"
brew "automake"
brew "bat"
brew "boost"
brew "cmake"
brew "coreutils"
brew "cowsay"
brew "go"
brew "dep"
brew "diff-so-fancy"
brew "docker", link: false
brew "docker-machine", link: false
brew "libyaml"
brew "docker-compose"
brew "elasticsearch@2.4", restart_service: true
brew "exa"
brew "fortune"
brew "fswatch"
brew "fzf"
brew "git"
brew "glide"
brew "gnupg"
brew "go@1.9", link: true
brew "hadoop"
brew "htop"
brew "hub"
brew "hyperscan"
brew "icu4c"
brew "libtool"
brew "imagemagick"
brew "jansson"
brew "jq"
brew "launch_socket_server", restart_service: true
brew "launchdns", restart_service: true
brew "lcov"
brew "openssl"
brew "libxml2"
brew "readline"
brew "python"
brew "macvim"
brew "md5sha1sum"
brew "memcached", restart_service: true
brew "mysql@5.7", restart_service: true
brew "ncdu"
brew "neovim"
brew "nginx", restart_service: true
brew "node"
brew "pkg-config"
brew "node-build"
brew "nodenv"
brew "noti"
brew "openssl@1.1"
brew "phantomjs"
brew "pidof"
brew "pinentry-mac"
brew "postgresql", restart_service: true
brew "postgresql@9.5", restart_service: true
brew "protobuf"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ripgrep"
brew "shellcheck"
brew "socat"
brew "softhsm"
brew "tldr"
brew "tmux"
brew "unrar"
brew "vim"
brew "wget"
brew "heroku/brew/heroku"
cask "docker"
cask "gitify"
cask "graphiql"
cask "vagrant"
cask "virtualbox"
cask "viscosity"
